#
# Use ubuntu trusty (14.04) with sudo privileges.
dist: trusty
sudo: required
language:
  - generic
cache:
  - apt

language: cpp
compiler:
  - gcc
  
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq qt5-default qttools5-dev
  - sudo apt-get install -qq gcc-4.7

#check repository
script:
  - cd CIFAR10visual
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - cd ..
  - cd knn
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - cd ..
  - cd linearSVM
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - cd ..
  - cd linearSoftmax
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - cd ..
  - cd 2layersNN
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - cd ..
