#
# Use ubuntu trusty (14.04) with sudo privileges.
dist: trusty
sudo: required
language:
  - generic
cache:
  - apt

language: cpp
compiler:
  - gcc
  
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq gcc-4.7

#check repository
script:
  - cd CIFAR10visual 
  - mkdir build
  - cd build
  - cmake ..
  - make

